url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Nicholas Choustikov" # the name of your site, e.g. ACME Corp.
description: "Astrophysics PhD Student in Oxford"
