menu:
#- {name: 'publications', url: '/publications'}
#- {name: 'courses', url: '/courses'}
#- {name: 'cv', url: '/cv'}
- {name: 'Contact', url: '/contact'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'fab fa-github', link: 'https://github.com/Chousti'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'fa fa-university', link: 'https://www.physics.ox.ac.uk/our-people/choustikov'}

contacts:
- {name: 'Nicholas Choustikov', title: 'Graduate Student', department: 'Sub-department of Astrophysics', institution: 'University of Oxford', institution_address: 'Keble Road, Oxford OX1 3RH', phone: '07512674717', email: 'nicholas.choustikov@physics.ox.ac.uk', office: 'Undercroft'} #, image: 'assets/img/contact.jpg'}
