menu:
- {name: 'Publications', url: '/publications'}
#- {name: 'courses', url: '/courses'}
#- {name: 'cv', url: '/cv'}
- {name: 'Contact', url: '/contact'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'fab fa-github', link: 'https://github.com/Chousti'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'fa fa-university', link: 'https://www.physics.ox.ac.uk/our-people/choustikov'}
- {icon: 'fa fa-rocket', link: 'https://ui.adsabs.harvard.edu/search/fq=%7B!type%3Daqp%20v%3D%24fq_database%7D&fq_database=database%3A%20astronomy&p_=0&q=pubdate%3A%5B2020-01%20TO%209999-12%5D%20author%3A(%22Choustikov%2C%20Nicholas%22)&sort=date%20desc%2C%20bibcode%20desc'}

contacts:
- {name: 'Nicholas Choustikov', title: 'Graduate Student', department: 'Sub-department of Astrophysics', institution: 'University of Oxford', institution_address: 'Keble Road, Oxford OX1 3RH', phone: '07512674717', email: 'nicholas.choustikov@physics.ox.ac.uk', office: 'Undercroft'} #, image: 'assets/img/contact.jpg'}
